import type { Lyrics } from "@syllary/shared";

/** Synced lyrics for the fixed demo clip (apps/api/assets/demo-clip.mp3).
 *  GENERATED by scripts/build-demo-clip.ts — re-run that script to regenerate
 *  rather than hand-editing the timings. */
export const DEMO_CLIP_SECONDS = 11;

export const DEMO_CLIP_LYRICS: Lyrics = {
  "language": "eng",
  "lines": [
    {
      "text": "Stomp, stomp, tiny feet.",
      "start": 0.579,
      "end": 2.74,
      "words": [
        {
          "text": "Stomp,",
          "start": 0.579,
          "end": 1.079
        },
        {
          "text": "stomp,",
          "start": 1.259,
          "end": 1.639
        },
        {
          "text": "tiny",
          "start": 1.879,
          "end": 2.359
        },
        {
          "text": "feet.",
          "start": 2.419,
          "end": 2.74
        }
      ],
      "section": "Verse 1"
    },
    {
      "text": "Boom, boom, monster beat.",
      "start": 3.139,
      "end": 5.179,
      "words": [
        {
          "text": "Boom,",
          "start": 3.139,
          "end": 3.599
        },
        {
          "text": "boom,",
          "start": 3.759,
          "end": 4.179
        },
        {
          "text": "monster",
          "start": 4.36,
          "end": 4.779
        },
        {
          "text": "beat.",
          "start": 4.9,
          "end": 5.179
        }
      ],
      "section": null
    },
    {
      "text": "Roar, roar, not too loud.",
      "start": 5.619,
      "end": 7.899,
      "words": [
        {
          "text": "Roar,",
          "start": 5.619,
          "end": 6.099
        },
        {
          "text": "roar,",
          "start": 6.219,
          "end": 6.699
        },
        {
          "text": "not",
          "start": 6.859,
          "end": 7.079
        },
        {
          "text": "too",
          "start": 7.139,
          "end": 7.319
        },
        {
          "text": "loud.",
          "start": 7.379,
          "end": 7.899
        }
      ],
      "section": null
    },
    {
      "text": "Jump, jump, shake the crowd!",
      "start": 8.099,
      "end": 10.239,
      "words": [
        {
          "text": "Jump,",
          "start": 8.099,
          "end": 8.399
        },
        {
          "text": "jump,",
          "start": 8.72,
          "end": 9.019
        },
        {
          "text": "shake",
          "start": 9.3,
          "end": 9.599
        },
        {
          "text": "the",
          "start": 9.659,
          "end": 9.719
        },
        {
          "text": "crowd!",
          "start": 9.779,
          "end": 10.239
        }
      ],
      "section": null
    }
  ]
};
