import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildSegments, type AspectRatio, type ImageQuality, type ImageSize } from "@syllary/shared";
import { buildBackdropPrompt, generateBackdrop } from "./openrouter-image.js";
import { normalizeFrameToJpeg, stitchLyricsVideo, type StitchSegment } from "./ffmpeg.js";
import { putObject } from "./r2.js";
import { DEMO_CLIP_LYRICS, DEMO_CLIP_SECONDS } from "./demo-clip-lyrics.js";

// A cheap, fast Slideshow render: still frames (the lyric line is rendered INTO
// each frame) + a single ffmpeg stitch. 16:9, Nano-Banana-2 "fast" frames at 2K
// (crisp at 1080p without the Pro-tier price).
const ASPECT: AspectRatio = "16:9";
const QUALITY: ImageQuality = "fast";
const SIZE: ImageSize = "2K";
const IMAGE_CONCURRENCY = 4;

/** True once the sample clip's lyrics have been generated by
 *  scripts/build-demo-clip.ts. The route uses it for a clearer 503. */
export const DEMO_CLIP_READY = DEMO_CLIP_LYRICS.lines.length > 0;

/** The bundled sample audio. Mirrors ffmpeg.ts resolveWatermarkPath: this module
 *  sits at a different depth in dev (apps/api/src/lib) vs the flattened prod
 *  bundle (apps/api/dist), so probe the known candidates and take the first that
 *  exists. */
function resolveDemoClipPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.resolve(here, "../../assets/demo-clip.mp3"), // dev: apps/api/src/lib → apps/api/assets
    path.resolve(here, "../assets/demo-clip.mp3"), //    prod bundle: apps/api/dist → apps/api/assets
    path.resolve(process.cwd(), "assets/demo-clip.mp3"), //         cwd = apps/api
    path.resolve(process.cwd(), "apps/api/assets/demo-clip.mp3"), // cwd = repo root
  ];
  return candidates.find((p) => existsSync(p)) ?? candidates[0]!;
}

async function mapPool<T>(items: T[], limit: number, fn: (item: T) => Promise<void>): Promise<void> {
  let cursor = 0;
  const worker = async (): Promise<void> => {
    while (cursor < items.length) {
      const i = cursor++;
      await fn(items[i]!);
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
}

/** Render the fixed demo clip into a ~10s Slideshow lyric video in the chosen
 *  style + scene description, upload it to R2, and return the object key. One
 *  frame per lyric line (the line rendered into the frame), then a single ffmpeg
 *  stitch + audio mux. Throws "DEMO_NOT_BUILT" when the clip lyrics are missing
 *  (run scripts/build-demo-clip.ts), otherwise the underlying render error. */
export async function renderDemoSlideshow(opts: {
  style: string;
  description: string;
  ownerHash: string;
}): Promise<string> {
  // Pinned to "line": the demo clip's look predates grouping and must not change.
  const segments = buildSegments(DEMO_CLIP_LYRICS, DEMO_CLIP_SECONDS, "line");
  if (segments.length === 0) throw new Error("DEMO_NOT_BUILT");

  const id = randomUUID();
  const workDir = path.join(os.tmpdir(), `syllary-demo-${id}`);
  await mkdir(workDir, { recursive: true });
  try {
    const stitch: StitchSegment[] = new Array(segments.length);
    await mapPool(segments, IMAGE_CONCURRENCY, async (seg) => {
      const prompt = buildBackdropPrompt({
        style: opts.style,
        lyricText: seg.text,
        aspectRatio: ASPECT,
        renderText: true,
        context: opts.description || undefined,
      });
      const raw = await generateBackdrop({
        style: opts.style,
        lineText: seg.text,
        aspectRatio: ASPECT,
        imageSize: SIZE,
        quality: QUALITY,
        renderText: true,
        promptOverride: prompt,
      });
      const buf = await normalizeFrameToJpeg(raw);
      const imageFile = path.join(workDir, `img_${seg.index}.jpg`);
      await writeFile(imageFile, buf);
      stitch[seg.index] = {
        index: seg.index,
        imageFile,
        clipStart: seg.clipStart,
        clipEnd: seg.clipEnd,
      };
    });

    const audioFile = path.join(workDir, "audio.mp3");
    await writeFile(audioFile, await readFile(resolveDemoClipPath()));
    const outFile = path.join(workDir, "demo.mp4");
    await stitchLyricsVideo({ workDir, segments: stitch, audioFile, aspectRatio: ASPECT, outFile });

    const key = `demo-video/${opts.ownerHash}/${id}.mp4`;
    await putObject(key, await readFile(outFile), "video/mp4");
    return key;
  } finally {
    await rm(workDir, { recursive: true, force: true }).catch(() => undefined);
  }
}
