import "../load-env.js";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { presignGet, putObject } from "../lib/r2.js";
import { transcribeWithScribe } from "../lib/fal-stt.js";
import { buildLyricsFromScribe } from "../lib/transcript.js";

/**
 * One-time setup for the demo lyric-video tool: transcribe the fixed sample clip
 * (apps/api/assets/demo-clip.mp3) and write its synced lyrics to
 * src/lib/demo-clip-lyrics.ts so the render is deterministic + free (no
 * per-request transcription). Run once with the fal.ai + R2 keys set:
 *
 *   pnpm --filter @syllary/api exec tsx src/scripts/build-demo-clip.ts
 *
 * Re-run only if you swap the sample clip. The demo endpoint stays a 503 until
 * this has run at least once.
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const CLIP = path.resolve(here, "../../assets/demo-clip.mp3");
const OUT = path.resolve(here, "../lib/demo-clip-lyrics.ts");

async function main(): Promise<void> {
  const audio = await readFile(CLIP);
  console.log(`[demo-clip] read ${CLIP} (${audio.length} bytes)`);

  // Park the clip in R2 so fal.ai's Scribe can fetch it by URL (it needs a
  // publicly-fetchable source; a 1h presigned R2 URL is plenty).
  const key = "demo-video/_source/demo-clip.mp3";
  await putObject(key, audio, "audio/mpeg");
  const url = await presignGet(key);

  console.log("[demo-clip] transcribing with Scribe…");
  const scribe = await transcribeWithScribe(url);
  const lyrics = await buildLyricsFromScribe(scribe);
  const seconds = Math.max(1, Math.ceil(lyrics.lines.at(-1)?.end ?? 10));
  console.log(`[demo-clip] ${lyrics.lines.length} lines, ~${seconds}s:`);
  for (const l of lyrics.lines) {
    console.log(`  ${l.start.toFixed(2)}–${l.end.toFixed(2)}  ${l.text}`);
  }

  const file = `import type { Lyrics } from "@syllary/shared";

/** Synced lyrics for the fixed demo clip (apps/api/assets/demo-clip.mp3).
 *  GENERATED by scripts/build-demo-clip.ts — re-run that script to regenerate
 *  rather than hand-editing the timings. */
export const DEMO_CLIP_SECONDS = ${seconds};

export const DEMO_CLIP_LYRICS: Lyrics = ${JSON.stringify(lyrics, null, 2)};
`;
  await writeFile(OUT, file, "utf8");
  console.log(`[demo-clip] wrote ${OUT}`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
