/** Genre suggestions for the public-details autosuggest. Free typing is always
 *  allowed — these are only hints. Backbone is the ID3v1 + Winamp-extended genre
 *  list (the canonical "all genres" set), cleaned of non-music / joke / offensive
 *  entries and supplemented with common modern genres ID3 predates. The most
 *  common genres lead the list so the empty-field dropdown surfaces useful picks;
 *  the long tail is grouped by family. */
export const GENRES: string[] = [
  // ---- Most common (lead the dropdown) ----
  "Pop",
  "Rock",
  "Hip Hop",
  "Rap",
  "Trap",
  "R&B",
  "Soul",
  "Indie",
  "Alternative",
  "Electronic",
  "EDM",
  "House",
  "Techno",
  "Dance",
  "Folk",
  "Country",
  "Metal",
  "Punk",
  "Jazz",
  "Blues",
  "Classical",
  "Reggae",
  "Latin",
  "Afrobeats",
  "K-Pop",
  "Funk",
  "Disco",
  "Gospel",
  "Ambient",
  "Lo-fi",
  "Instrumental",
  "Soundtrack",
  "Singer-Songwriter",
  "Acoustic",
  "World",
  "Experimental",

  // ---- Rock ----
  "Classic Rock",
  "Alternative Rock",
  "Indie Rock",
  "Hard Rock",
  "Soft Rock",
  "Punk Rock",
  "Post-Punk",
  "Pop Punk",
  "Grunge",
  "Garage Rock",
  "Psychedelic Rock",
  "Progressive Rock",
  "Art Rock",
  "Glam Rock",
  "Folk Rock",
  "Southern Rock",
  "Space Rock",
  "Math Rock",
  "Post-Rock",
  "Krautrock",
  "Surf Rock",
  "Rockabilly",
  "Rock 'n' Roll",
  "Shoegaze",
  "Emo",
  "Britpop",
  "New Wave",

  // ---- Metal ----
  "Heavy Metal",
  "Death Metal",
  "Black Metal",
  "Thrash Metal",
  "Doom Metal",
  "Power Metal",
  "Nu Metal",
  "Metalcore",
  "Deathcore",
  "Grindcore",
  "Hardcore",
  "Symphonic Metal",
  "Folk Metal",
  "Gothic Metal",
  "Industrial Metal",
  "Progressive Metal",

  // ---- Pop ----
  "Indie Pop",
  "Synthpop",
  "Electropop",
  "Dream Pop",
  "Power Pop",
  "Dance Pop",
  "Art Pop",
  "Hyperpop",
  "J-Pop",
  "C-Pop",
  "Teen Pop",
  "Pop Rock",

  // ---- Hip Hop ----
  "Drill",
  "Boom Bap",
  "Gangsta Rap",
  "Conscious Hip Hop",
  "Cloud Rap",
  "Grime",
  "Crunk",
  "G-Funk",
  "Phonk",
  "Trip Hop",

  // ---- R&B / Soul / Funk ----
  "Neo-Soul",
  "Contemporary R&B",
  "Motown",
  "Doo-Wop",
  "Quiet Storm",

  // ---- Electronic ----
  "Deep House",
  "Tech House",
  "Progressive House",
  "Electro House",
  "Trance",
  "Psytrance",
  "Dubstep",
  "Drum & Bass",
  "Jungle",
  "Breakbeat",
  "Garage",
  "UK Garage",
  "Future Bass",
  "Synthwave",
  "Vaporwave",
  "Downtempo",
  "IDM",
  "Glitch",
  "Electro",
  "Electroclash",
  "Big Beat",
  "Hardstyle",
  "Hardcore Techno",
  "Gabber",
  "Eurodance",
  "Chillout",
  "Lounge",
  "EBM",
  "Industrial",
  "Acid House",
  "Bass",

  // ---- Jazz / Blues ----
  "Smooth Jazz",
  "Acid Jazz",
  "Bebop",
  "Swing",
  "Big Band",
  "Fusion",
  "Free Jazz",
  "Dixieland",
  "Rhythm and Blues",
  "Boogie-Woogie",

  // ---- Folk / Country ----
  "Indie Folk",
  "Americana",
  "Bluegrass",
  "Country Pop",
  "Country Rock",
  "Alt-Country",
  "Honky Tonk",
  "Celtic",
  "Cajun",
  "Zydeco",

  // ---- Classical ----
  "Baroque",
  "Opera",
  "Orchestral",
  "Symphony",
  "Chamber Music",
  "Choral",
  "Contemporary Classical",
  "Neoclassical",
  "Sonata",

  // ---- Latin / World / Regional ----
  "Reggaeton",
  "Salsa",
  "Bachata",
  "Merengue",
  "Cumbia",
  "Bossa Nova",
  "Samba",
  "Tango",
  "Flamenco",
  "Mariachi",
  "Latin Pop",
  "Latin Jazz",
  "Afrobeat",
  "Amapiano",
  "Highlife",
  "Soca",
  "Calypso",
  "Dancehall",
  "Ska",
  "Dub",
  "Rocksteady",
  "Bhangra",
  "Bollywood",
  "Anime",
  "City Pop",
  "Polka",
  "Schlager",
  "Chanson",
  "Fado",
  "Klezmer",

  // ---- Other / Misc ----
  "New Age",
  "Meditation",
  "Gothic",
  "Darkwave",
  "Avant-Garde",
  "Noise",
  "Drone",
  "A Cappella",
  "Film Score",
  "Video Game",
  "Musical",
  "Showtunes",
  "Christmas",
  "Holiday",
  "Children's Music",
  "Comedy",
  "Spoken Word",
  "Marching Band",
];
